spring.application.name=grpc-server-tomcat-secure
server.port=9090
server.http2.enabled=true
spring.security.user.name=user
spring.security.user.password=user
management.otlp.metrics.export.enabled=false
