spring.application.name=auth-server
server.port=9000
spring.security.oauth2.authorizationserver.issuer=http://localhost:9000
spring.security.oauth2.authorizationserver.client.oidc-client.registration.client-id=spring
spring.security.oauth2.authorizationserver.client.oidc-client.registration.client-secret={noop}secret
spring.security.oauth2.authorizationserver.client.oidc-client.registration.client-authentication-methods[0]=client_secret_basic
spring.security.oauth2.authorizationserver.client.oidc-client.registration.authorization-grant-types[0]=client_credentials
spring.security.oauth2.authorizationserver.client.oidc-client.registration.scopes[0]=openid
spring.security.oauth2.authorizationserver.client.oidc-client.registration.scopes[1]=profile
management.otlp.metrics.export.enabled=false
